import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest'
import {render,screen,fireEvent,within,cleanup} from '@testing-library/react'
import {MemoryRouter,Routes,Route} from 'react-router-dom'
import SocialClientApprove from '../pages/r/SocialClientApprove'
const cards=[{id:'a',title:'Vídeo A',client:'Cliente A',stage:'aguardando',revision:1,version:3,assets:[],caption:'Legenda A'},{id:'b',title:'Vídeo B',client:'Cliente A',stage:'aguardando',revision:2,version:5,assets:[],caption:'Legenda B'}]
let request:ReturnType<typeof vi.fn>
const show=()=>render(<MemoryRouter initialEntries={['/aprovar/cliente/'+'a'.repeat(64)]}><Routes><Route path="/aprovar/cliente/:token" element={<SocialClientApprove/>}/></Routes></MemoryRouter>)
beforeEach(()=>{request=vi.fn(async(_url,options)=>{if(!options)return {ok:true,json:async()=>({client:'Cliente A',cards})};const body=JSON.parse(options.body);return {ok:true,json:async()=>({card:{...cards.find(c=>c.id===body.id),stage:body.action==='cliente_aprovar'?'aprovado':'ajustes'}})}});vi.stubGlobal('fetch',request)})
afterEach(()=>{cleanup();vi.unstubAllGlobals()})
describe('client reviews several pieces on one page',()=>{
 it('approves only the selected piece and preserves the other pending form',async()=>{show();const a=await screen.findByRole('article',{name:'Vídeo A'}),b=screen.getByRole('article',{name:'Vídeo B'});fireEvent.change(within(a).getByRole('textbox',{name:'Seu nome'}),{target:{value:'Maria'}});expect(within(b).getByRole('textbox',{name:'Seu nome'})).toHaveValue('Maria');fireEvent.click(within(a).getByRole('button',{name:'Aprovar esta versão'}));await within(a).findByText('Aprovação registrada.');expect(screen.getByRole('status')).toHaveTextContent('1 publicação aguardando');expect(within(b).getByRole('button',{name:'Aprovar esta versão'})).toBeEnabled();expect(JSON.parse(request.mock.calls[1][1].body)).toMatchObject({id:'a',version:3,action:'cliente_aprovar',name:'Maria'});expect(request).toHaveBeenCalledTimes(2)})
 it('sends the reason for the right piece and keeps it separate from approval',async()=>{show();const b=await screen.findByRole('article',{name:'Vídeo B'});fireEvent.change(within(b).getByRole('textbox',{name:'Seu nome'}),{target:{value:'Maria'}});fireEvent.click(within(b).getByRole('button',{name:'Pedir alteração'}));fireEvent.change(within(b).getByRole('textbox',{name:'O que você deseja alterar?'}),{target:{value:'Trocar a frase aos 15 segundos.'}});fireEvent.click(within(b).getByRole('button',{name:'Enviar pedido de alteração'}));await within(b).findByText('Pedido de alteração registrado.');expect(JSON.parse(request.mock.calls[1][1].body)).toMatchObject({id:'b',version:5,action:'cliente_ajustes',reason:'Trocar a frase aos 15 segundos.'})})
 it('does not claim approval when a newer version caused a conflict',async()=>{request.mockImplementationOnce(async()=>({ok:true,json:async()=>({client:'Cliente A',cards})})).mockImplementationOnce(async()=>({ok:false,json:async()=>({error:'Esta peça mudou. Atualize a página.'})}));show();const a=await screen.findByRole('article',{name:'Vídeo A'});fireEvent.change(within(a).getByRole('textbox',{name:'Seu nome'}),{target:{value:'Maria'}});fireEvent.click(within(a).getByRole('button',{name:'Aprovar esta versão'}));expect(await within(a).findByRole('alert')).toHaveTextContent('Esta peça mudou');expect(screen.getByRole('status')).toHaveTextContent('2 publicações');expect(screen.queryByText('Aprovação registrada.')).toBeNull()})
 it('keeps an empty client link useful for future deliveries',async()=>{request.mockResolvedValue({ok:true,json:async()=>({client:'Cliente A',cards:[]})});show();expect(await screen.findByText('Tudo conferido por aqui.')).toBeVisible();expect(screen.getByText(/neste mesmo link/)).toBeVisible()})
})
