import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest'
import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react'
import ApprovalLink from '../components/social/ApprovalLink'
const url='https://central.svicompany.com.br/aprovar/social/'+'a'.repeat(64)
let write=vi.fn(),legacyCopy=vi.fn()
beforeEach(()=>{write=vi.fn().mockResolvedValue(undefined);legacyCopy=vi.fn().mockReturnValue(false);Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:write}});Object.defineProperty(document,'execCommand',{configurable:true,value:legacyCopy})})
afterEach(cleanup)
describe('client approval link copy',()=>{
 it('generates the link in place and copies only on the explicit copy button',async()=>{const generate=vi.fn(async()=>url);render(<ApprovalLink url="" legacy={false} routingPending onGenerate={generate}/>);fireEvent.click(screen.getByRole('button',{name:'Gerar link do cliente'}));await screen.findByRole('button',{name:'Copiar link do cliente'});expect(write).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Copiar link do cliente'}));await screen.findByText('Link copiado. Agora é só colar na conversa com o cliente.');expect(write).toHaveBeenCalledWith(url);expect(generate).toHaveBeenCalledTimes(1)})
 it('copies a reopened existing link without generating another one',async()=>{const generate=vi.fn();render(<ApprovalLink url={url} legacy={false} routingPending={false} onGenerate={generate}/>);fireEvent.click(screen.getByRole('button',{name:'Copiar link do cliente'}));await waitFor(()=>expect(write).toHaveBeenCalledWith(url));expect(generate).not.toHaveBeenCalled()})
 it('falls back to copying the visible selected URL when clipboard API is denied',async()=>{write.mockRejectedValue(new Error('denied'));legacyCopy.mockReturnValue(true);render(<ApprovalLink url={url} legacy={false} routingPending={false} onGenerate={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:'Copiar link do cliente'}));await screen.findByText('Link copiado. Agora é só colar na conversa com o cliente.');expect(legacyCopy).toHaveBeenCalledWith('copy')})
 it('never claims success when all automatic copying is blocked',async()=>{write.mockRejectedValue(new Error('denied'));render(<ApprovalLink url={url} legacy={false} routingPending={false} onGenerate={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:'Copiar link do cliente'}));await screen.findByText(/O navegador bloqueou/);expect(screen.queryByText('Link copiado')).toBeNull();const input=screen.getByRole('textbox',{name:'Link de aprovação do cliente'}) as HTMLInputElement;expect(input.selectionStart).toBe(0);expect(input.selectionEnd).toBe(url.length)})
 it('shows generation errors beside the button',async()=>{render(<ApprovalLink url="" legacy={false} routingPending={false} onGenerate={async()=>{throw new Error('Esta versão mudou.')}}/>);fireEvent.click(screen.getByRole('button',{name:'Gerar link do cliente'}));expect(await screen.findByRole('alert')).toHaveTextContent('Esta versão mudou.');expect(write).not.toHaveBeenCalled()})
 it('does not expose an old version through the copy action while edits are unsaved',()=>{render(<ApprovalLink url={url} legacy={false} routingPending={false} disabledReason="Salve as alterações." onGenerate={vi.fn()}/>);expect(screen.getByRole('button',{name:'Copiar link do cliente'})).toBeDisabled()})
 it('explains replacement before regenerating a legacy address',()=>{render(<ApprovalLink url="" legacy routingPending onGenerate={vi.fn()}/>);expect(screen.getByText(/substituirá o anterior/)).toBeVisible();expect(screen.getByRole('button',{name:'Gerar novo link do cliente'})).toBeEnabled()})
})
