import { beforeEach, describe, expect, it, vi } from 'vitest'
import { createHash } from 'node:crypto'
import type { SocialCard } from '../../api/_lib/social-domain'
const mock=vi.hoisted(()=>({read:vi.fn(),from:vi.fn(),eq:vi.fn(),download:vi.fn()}))
vi.mock('node:fs/promises',()=>({readFile:mock.read,default:{readFile:mock.read}}))
vi.mock('../../api/_lib/supabase',()=>({createAdminClient:()=>({from:mock.from,storage:{from:()=>({download:mock.download})}})}))
import { handleSocialShare, socialShareHTML, socialShareMeta } from '../../api/_lib/social-share'
const token='a'.repeat(64)
const shell='<html lang="en"><head><title>Central Svi</title><meta property="og:image" content="LOGO"><meta name="twitter:description" content="OLD"><meta name="description" content="OLD"></head><body><div id="root"></div><script src="/assets/app.js"></script></body></html>'
const card={id:'test',client:'Clínica',title:'Meu vídeo',revision:2,selected_assets:['b','a'],assets:[{id:'secret',name:'INTERNAL',type:'video/mp4',path:'private',thumbnail:'secret.jpg'},{id:'a',name:'Primeiro',type:'image/png',path:'image.png'},{id:'b',name:'Vídeo.MP4',type:'video/mp4',storage:'drive',path:'drive:123',thumbnail:'previews/video.jpg'}],note:'INTERNAL_NOTE',source_description:'INTERNAL_BRIEF',token_expires_at:'2099-01-01T00:00:00Z'} as SocialCard
function response(){return {code:0,headers:{} as Record<string,string>,body:undefined as unknown,status(n:number){this.code=n;return this},setHeader(k:string,v:string){this.headers[k]=v;return this},send(body:unknown){this.body=body;return this},end(){return this}}}
beforeEach(()=>{vi.clearAllMocks();mock.read.mockResolvedValue(shell);mock.eq.mockReturnValue({maybeSingle:async()=>({data:card,error:null})});mock.from.mockReturnValue({select:()=>({eq:mock.eq})});mock.download.mockResolvedValue({data:{type:'image/jpeg',size:3,arrayBuffer:async()=>new Uint8Array([255,216,255]).buffer},error:null})})
describe('approval link previews',()=>{
 it('uses only selected assets, in approval order',()=>{const m=socialShareMeta(card,token);expect(m.asset?.id).toBe('b');expect(m.image).toBe(`https://central.svicompany.com.br/aprovar/social/${token}/preview.jpg`);expect(m.description).toContain('2 arquivos')})
 it('replaces generic metadata in initial HTML while preserving the app',()=>{const html=socialShareHTML(shell,socialShareMeta(card,token));expect(html).toContain('Clínica · Meu vídeo');expect(html).toContain('/assets/app.js');expect(html).toContain('lang="pt-BR"');expect(html).not.toMatch(/LOGO|OLD|INTERNAL/);expect((html.match(/property="og:image"/g)||[]).length).toBe(1)})
 it('escapes client-controlled text instead of injecting HTML',()=>{const html=socialShareHTML(shell,socialShareMeta({...card,title:'"><script>alert(1)</script>'},token));expect(html).not.toContain('<script>alert');expect(html).toContain('&lt;script&gt;')})
 it('rejects malformed tokens before reading any card',async()=>{const r=response();await handleSocialShare({method:'GET',query:{token:'test'}} as never,r as never);expect(r.code).toBe(404);expect(mock.from).not.toHaveBeenCalled()})
 it('checks the token hash and emits metadata without requiring browser JavaScript',async()=>{const r=response();await handleSocialShare({method:'GET',query:{token},headers:{'user-agent':'WhatsApp/2'}} as never,r as never);expect(mock.eq).toHaveBeenCalledWith('token_hash',createHash('sha256').update(token).digest('hex'));expect(r.code).toBe(200);expect(r.body).toContain('property="og:image"');expect(r.headers['Cache-Control']).toBe('private, no-store')})
 it.each([null,{...card,token_expires_at:'2020-01-01'}, {...card,token_expires_at:'invalid'}, {...card,ingest_pending:true}, {...card,selected_assets:[]}])('does not expose expired/revoked/pending/unselected pieces',async(data)=>{mock.eq.mockReturnValue({maybeSingle:async()=>({data,error:null})});const r=response();await handleSocialShare({method:'GET',query:{token,image:'1'}} as never,r as never);expect(r.code).toBe(404);expect(mock.download).not.toHaveBeenCalled();expect(JSON.stringify(r.body)).not.toContain(card.title)})
 it('serves only the authorized cover, without a public bucket or signed URL redirect',async()=>{const r=response();await handleSocialShare({method:'GET',query:{token,image:'1',path:'secret.jpg'}} as never,r as never);expect(mock.download).toHaveBeenCalledWith('previews/video.jpg');expect(r.code).toBe(200);expect(r.headers['Content-Type']).toBe('image/jpeg');expect(Buffer.isBuffer(r.body)).toBe(true);expect(r.headers.Location).toBeUndefined()})
 it('supports HEAD without a body',async()=>{const r=response();await handleSocialShare({method:'HEAD',query:{token}} as never,r as never);expect(r.code).toBe(200);expect(r.body).toBeUndefined()})
 it('does not accept a write action through the preview route',async()=>{const r=response();await handleSocialShare({method:'POST',query:{token}} as never,r as never);expect(r.code).toBe(405);expect(mock.from).not.toHaveBeenCalled()})
})
