import {useCallback,useEffect,useRef,useState} from 'react'
import {Loader2,Send,CalendarClock,ImagePlus} from 'lucide-react'
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog'
import {Button} from '@/components/ui/button'
import {Textarea} from '@/components/ui/textarea'
import {Input} from '@/components/ui/input'
import {socialApi,type Card,socialDate} from '@/lib/social-board'
import CaptionAssistant from './CaptionAssistant'
type Account={id:string;username:string;name:string}
type Job={id:string;status:string;account_username:string;format:string;scheduled_at:string;error?:string;permalink?:string}
const labels:Record<string,string>={queued:'Na fila de publicação',preparing:'Preparando os arquivos',processing:'Instagram processando',publishing:'Enviando ao Instagram',uncertain:'Conferindo o envio',published:'Publicado',failed:'Publicação não concluída',canceled:'Programação cancelada'}
const active=(j:Job|null)=>!!j&&['queued','preparing','processing','publishing','uncertain'].includes(j.status)
export default function PublicationComposer({ids,cards,onClose,onChanged,schedule=false}:{ids:string[];cards:Card[];onClose:()=>void;onChanged:()=>void;schedule?:boolean}){
 const [id,setId]=useState(ids[0]),[card,setCard]=useState<Card|null>(null),[accounts,setAccounts]=useState<Account[]>([]),[job,setJob]=useState<Job|null>(null)
 const [account,setAccount]=useState(''),[format,setFormat]=useState(''),[caption,setCaption]=useState(''),[when,setWhen]=useState(schedule?'later':'now'),[date,setDate]=useState('')
 const [cover,setCover]=useState<{path:string;preview:string}|null>(null),[offset,setOffset]=useState(0),[moment,setMoment]=useState(0)
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false)
 const video=useRef<HTMLVideoElement>(null),request=useRef(crypto.randomUUID()),read=useRef(0),submitted=useRef(false)
 const load=useCallback(async(initialize=false)=>{const n=++read.current;try{const d=await socialApi('?publication=1&id='+encodeURIComponent(id));if(n!==read.current)return;setCard(d.card);setAccounts(d.accounts);setJob(d.publication);if(initialize){setCaption(d.card.caption);const selected=d.card.assets.filter((a:any)=>d.card.selected_assets.includes(a.id));setFormat(selected.length>1?'carousel':selected[0]?.type.startsWith('video/')?'reel':'image')}}catch(e){if(n===read.current)setError((e as Error).message)}finally{if(n===read.current)setLoading(false)}},[id])
 useEffect(()=>{setLoading(true);setCard(null);setAccount('');setCover(null);setOffset(0);setMoment(0);setError('');setDone(false);submitted.current=false;request.current=crypto.randomUUID();void load(true);return()=>{read.current++}},[load])
 useEffect(()=>{if(!active(job))return;const t=setInterval(()=>void load(),7000);return()=>clearInterval(t)},[job?.status,load])
 useEffect(()=>{if(job?.status==='failed'){request.current=crypto.randomUUID();submitted.current=false}},[job?.id,job?.status])
 const completed=card?.stage==='postado'||job?.status==='published'
 const files=card?.selected_assets.map(id=>card.assets.find(a=>a.id===id)).filter(Boolean)||[],first=files[0],locked=busy||active(job)||completed
 const chooseCover=async(file:File)=>{
  if(!file.type.startsWith('image/'))return setError('Escolha uma imagem para a capa.')
  setBusy(true);setError('')
  try{const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas'),scale=Math.min(1,1080/bitmap.width,1920/bitmap.height);canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const d=await socialApi('',{action:'publication_cover',image:canvas.toDataURL('image/jpeg',0.9)});setCover(d)}catch(e){setError((e as Error).message)}finally{setBusy(false)}
 }
 const submit=async()=>{
  if(!card||busy||locked)return
  if(!account)return setError('Escolha a conta do Instagram que receberá esta peça.')
  if(when==='later'&&!date)return setError('Escolha o dia e a hora da postagem.')
  setBusy(true);setError('');submitted.current=true
  try{const d=await socialApi('',{action:'publication_enqueue',id:card.id,version:card.version,request_id:request.current,confirmed:true,account_id:account,format,caption,when,scheduled_at:when==='later'?new Date(date+':00-03:00').toISOString():null,cover_path:cover?.path||null,cover_offset_ms:offset});setJob(d.publication);setDone(true);onChanged();void load()}catch(e){setError((e as Error).message);await load()}finally{setBusy(false)}
 }
 // An edit after a failed request represents a new intent; successful/pending jobs stay locked.
 const revise=()=>{if(submitted.current){request.current=crypto.randomUUID();submitted.current=false}}
 const cancel=async()=>{if(!card||!job||busy)return;setBusy(true);setError('');try{await socialApi('',{action:'publication_cancel',id:card.id,version:card.version,job_id:job.id});request.current=crypto.randomUUID();setDone(false);onChanged();await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose()}}><DialogContent className="w-[calc(100%-1rem)] max-w-3xl max-h-[92dvh] overflow-y-auto p-4 sm:p-6" onPointerDownOutside={e=>{if(busy)e.preventDefault()}} onEscapeKeyDown={e=>{if(busy)e.preventDefault()}}><DialogHeader><DialogTitle>{schedule?'Programar postagem':card?.stage==='aprovado'?'Peça aprovada. Publicar agora?':'Publicar ou programar'}</DialogTitle><DialogDescription>Confira a conta, a legenda e a capa. O envio começa depois da sua confirmação.</DialogDescription></DialogHeader>
 {ids.length>1&&<label className="text-sm">Peças aprovadas<select aria-label="Peça para publicar" value={id} disabled={busy} onChange={e=>setId(e.target.value)} className="mt-2 w-full h-11 border rounded-lg bg-background px-3">{ids.map(id=><option value={id} key={id}>{cards.find(c=>c.id===id)?.title||id}</option>)}</select></label>}
 {loading?<p className="flex items-center gap-2 py-8"><Loader2 className="h-5 w-5 animate-spin"/>Carregando publicação…</p>:card&&<>
 <div><p className="text-xs uppercase tracking-wider text-primary">{card.client}</p><h3 className="font-medium mt-1">{card.title}</h3></div>
 {job&&<div className="rounded-xl border bg-muted/30 p-3 space-y-2" role="status"><p className="font-medium">{labels[job.status]||job.status} · @{job.account_username}</p><p className="text-sm text-muted-foreground">{socialDate(job.scheduled_at)}{active(job)?' · Você pode fechar esta janela.':''}</p>{job.error&&<p className="text-sm">{job.error}</p>}{done&&active(job)&&<p className="text-sm">Postado será marcado quando o Instagram confirmar.</p>}{job.permalink&&<a href={job.permalink} target="_blank" rel="noreferrer" className="text-primary underline">Ver no Instagram</a>}{['queued','preparing','processing','failed'].includes(job.status)&&<Button variant="outline" size="sm" disabled={busy} onClick={()=>void cancel()}>Cancelar programação</Button>}</div>}
 {completed&&!job&&<p role="status" className="text-sm">Esta peça já está em Postado. Consulte o registro de publicação nos detalhes.</p>}
 {!active(job)&&!completed&&<div className="grid gap-5 sm:grid-cols-[minmax(0,1fr)_minmax(0,1.4fr)]">
 <div className="space-y-3 min-w-0">{first?.type.startsWith('video/')?<><video ref={video} key={first.id} controls playsInline preload="metadata" poster={first.preview} src={first.playback_url||first.url} className="w-full max-h-80 rounded-xl bg-black object-contain" onTimeUpdate={e=>setMoment(e.currentTarget.currentTime)} />{format==='reel'&&<><Button className="w-full" variant="outline" disabled={busy} onClick={()=>{setOffset(Math.round((video.current?.currentTime||0)*1000));setCover(null);revise()}}>Usar momento {moment.toFixed(1)}s como capa</Button><p className="text-xs text-muted-foreground">{cover?'Capa enviada por você.':`Capa no instante ${(offset/1000).toFixed(1)}s do vídeo.`}</p><label className="flex min-h-11 cursor-pointer items-center justify-center gap-2 rounded-lg border p-2 text-sm"><ImagePlus className="h-4 w-4"/>Enviar outra capa<input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f){revise();void chooseCover(f)}e.target.value=''}}/></label>{cover&&<img src={cover.preview} alt="Capa escolhida" className="max-h-52 w-full object-contain rounded-lg"/>}</>}</>:<div className="grid grid-cols-2 gap-2">{files.map(a=>a&&<img key={a.id} src={a.url||a.preview} alt={a.name} className="w-full rounded-lg object-contain"/>)}</div>}<p className="text-xs text-muted-foreground">{files.length} arquivo{files.length===1?'':'s'} · ordem da peça</p></div>
 <div className="space-y-4 min-w-0"><label className="block text-sm font-medium">Conta do Instagram<select aria-label="Conta do Instagram" value={account} onChange={e=>{setAccount(e.target.value);revise()}} disabled={busy} className="mt-2 w-full h-11 rounded-lg border bg-background px-3"><option value="">Selecione a conta do cliente</option>{accounts.map(a=><option key={a.id} value={a.id}>@{a.username} · {a.name}</option>)}</select></label><label className="block text-sm font-medium">Formato<select value={format} disabled={busy} onChange={e=>{setFormat(e.target.value);revise()}} className="mt-2 w-full h-11 rounded-lg border bg-background px-3">{files.length>1?<option value="carousel">Carrossel</option>:<><option value={first?.type.startsWith('video/')?'reel':'image'}>{first?.type.startsWith('video/')?'Reels':'Imagem no feed'}</option><option value="story">Story</option></>}</select></label>{format!=='story'&&<><label className="block text-sm font-medium">Legenda<Textarea aria-label="Legenda da publicação" value={caption} onChange={e=>{setCaption(e.target.value);revise()}} disabled={busy} rows={7} maxLength={2200} className="mt-2 text-base"/></label><p className="text-xs text-muted-foreground text-right">{caption.length}/2.200</p><CaptionAssistant card={card} disabled={busy} onGenerated={v=>{setCaption(v);revise()}}/></>}
 <fieldset className="space-y-2"><legend className="text-sm font-medium mb-2">Quando publicar?</legend><div className="flex flex-wrap gap-4"><label className="flex min-h-11 items-center gap-2"><input type="radio" checked={when==='now'} disabled={busy} onChange={()=>{setWhen('now');revise()}}/>Agora</label><label className="flex min-h-11 items-center gap-2"><input type="radio" checked={when==='later'} disabled={busy} onChange={()=>{setWhen('later');revise()}}/>Escolher horário</label></div>{when==='later'&&<label className="block text-sm">Data e hora · Belém (UTC−3)<Input type="datetime-local" value={date} disabled={busy} onChange={e=>{setDate(e.target.value);revise()}} className="mt-2 text-base"/></label>}</fieldset></div></div>}
 </>}
 {error&&<p role="alert" className="text-sm text-destructive whitespace-pre-wrap">{error}</p>}
 <div className="flex flex-wrap justify-end gap-2 border-t pt-4"><Button variant="outline" disabled={busy} onClick={onClose}>{active(job)||completed?'Fechar':'Agora não'}</Button>{card&&!active(job)&&!completed&&<Button disabled={busy||loading||!account||caption.length>2200} onClick={()=>void submit()}>{busy?<Loader2 className="h-4 w-4 animate-spin"/>:when==='now'?<Send className="h-4 w-4"/>:<CalendarClock className="h-4 w-4"/>}{when==='now'?'Publicar agora':'Programar postagem'}</Button>}</div>
 </DialogContent></Dialog>
}
